xsolve_crawler_homepage:
    pattern:  /
    defaults: { _controller: XsolveCrawlerBundle:Crawler:index }
xsolve_crawler_search:
    pattern:  /search
    defaults: { _controller: XsolveCrawlerBundle:Crawler:search}
